export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const PROFILE_ROUTE = '/profile'
export const SELLER_ROUTE = '/seller/:id'
export const ADV_ROUTE = '/adv/:id'
export const MYADV_ROUTE = '/profile/adv/:id'
